fix: DesignForExtension
Class 'BaseSchema' looks like designed for extension (can be subclassed), but the method 'isValid' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'BaseSchema' final or making the method 'isValid' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
Error: eckstyle] [ERROR] /home/runner/work/java-project-78/java-project-78/app/src/main/java/hexlet/code/schemas/BaseSchema.java:20:5: Class 'BaseSchema' looks like designed for extension (can be subclassed), but the method 'addCheck' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'BaseSchema' final or making the method 'addCheck' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]